### ISSUE TITLE
App经常闪退和很多歌只能试听30秒以及在连接使用了VPS/VPN/SS/SSR/WireGuard等节点后就不能用了

### ISSUE THREAD

**Issue by Subtly7360** [listen1/listen1_mobile#183]
Mobile Phone models: OnePlus 9 5G (LE2115)
System Version: OxygenOS 13(LE2115_11_F.21 , 5.4.147-qgki-g1e98a35e31f0)
Listen1 Version: V0.8.2

- APP经常听着听着就自动闪退。这是闪退log：
```
type: crash
osVersion: OnePlus/OnePlus9/OnePlus9:13/TQ3A.230605.012/eng.emy.20230621.093501:user/release-keys
package: com.listen1.app:1
process: com.listen1.app

com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 'l.nowplayingTrack.id')

This error is located at:
    in w
    in Connect(w)
    in RCTView
    in t
    in Styled(styled.RCTView)
    in t
    in v
    in Connect(v)
    in c
    in f
    in h
    in RCTView
    in Unknown
    in k
    in Root
    in RCTView
    in b, stack:
value@896:3269
kn@91:30460
Or@91:47414
na@91:72881
ra@91:73371
Oa@91:80972
Wa@91:80310
Ue@91:83367
De@91:13673
We@91:13846
receiveEvent@91:14222
value@30:3311
<unknown>@30:822
value@30:2565
value@30:794
value@-1

	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
	at java.lang.Thread.run(Thread.java:1012)

```

- 很多歌曲只能试听30秒。
- Listen1的酷我音乐很多歌曲都提示无法收听，请到酷我音乐下载最新App。
- 搜索完QQ栏一直是处于转圈不可用的状态的，PC版的却现有所有栏都可用。
- 为啥listen1_mobile版，输入歌名搜索，没有All Music(Beta)这一栏？有些歌曲PC版Listen1就有，反而mobile版就变没有了，即使有也是无法播放的，但PC版就可以播放收听，比如：尤静波-五毛 ， 尤静波-哑巴。
- 有些歌曲在所有Listen1版里搜都没有，可在酷狗官网搜就有这个版本，比如：顾汝深-撕心的痛(DJ版)
- 在使用了其他国家的节点后Listen1就不能播放歌曲了，希望就算连接使用了其他非中国大陆节点服务器也能毫无影响继续播放音乐。（即做到无地区限制，或许可以通过自动检测然后自动启用代理来实现.）

**Comment by xlsw** [comment]
你应该去你的梯子里设置非全局非全应用，你这样把手机所有数据都走代理，也不怕隐私泄露👍

**Comment by Subtly7360** [comment]
PC用的是[v2rayN](https://github.com/2dust/v2rayN/releases) 貌似不能单独设置哪些应用不走代理，手机用的是Surfboard也没看到能单独设置哪些应用不走代理的。
另外，手机的Listen1的酷我音乐很多歌曲都提示无法收听，请到酷我音乐下载最新App才能收听。
------- Original Message -------

**Comment by fryzdman** [comment]
用完梯子后就不能用了  重新安装也安装不了！怎么解决呀
